title: KT Justis
email: neuroconvergent@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  suffering
domain: justisk.github.io
baseurl: ""
url: https://justisk.github.io

# Build settings
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    github: JustisK
plugins:
  - jekyll-feed
  - jekyll-remote-theme
